### ISSUE TITLE
ModuleNotFoundError: No module named 'aliyunsdkcore'

### ISSUE THREAD

**Issue by whitepapercg** [modelscope/scepter#70]
Torch version: 2.4.1+cu121
no xformers and flash-attn

```
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [7 lines of output]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\Deniaud\AppData\Local\Temp\pip-install-htrhgxfp\aliyun-python-sdk-core_b48ccf81dab94fd0a3aa5081b20ba5cc\setup.py", line 41, in <module>
[!]       VERSION = __import__(PACKAGE).__version__
[!]                 ^^^^^^^^^^^^^^^^^^^
[!]   ModuleNotFoundError: No module named 'aliyunsdkcore'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
 [!]E:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\scepter\scepter\workflow copy to E:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Scepter success!
 Traceback (most recent call last):
[!]   File "E:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\scepter\install.py", line 22, in <module>
[!]     subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'scepter'])
[!]   File "subprocess.py", line 413, in check_call
[!] subprocess.CalledProcessError: Command '['E:\\SD\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'scepter']' returned non-zero exit status 1.
install/(de)activation script failed: E:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\scepter
```

Earlier versions of aliyunsdkcore install without problems, but then it is not possible to install scepter due to lack of compatibility.

**Comment by yaosheng216** [comment]
You can try upgrade pip or update python version.

**Comment by whitepapercg** [comment]
> You can try upgrade pip or update python version.

Thanks! Yesterday I reinstalled ComfyUI and updated pip to the latest version.

aliyunsdkcore got install successfully, as well as scepter, but when running and importing Scepter, I get the following error:
`ComfyUI-Scepter module for custom nodes: cannot import name 'find_loader' from 'importlib'`

Python 3.12.4

**Comment by whitepapercg** [comment]
Installing Python 3.10.15 helped resolve this issue. Continue attempts to run in ComfyUI here https://github.com/modelscope/scepter/issues/94
